### ISSUE TITLE
Switch RediSearch text field to tag fields

### ISSUE THREAD

**Issue by alancleary** [legumeinfo/microservices#47]
RediSearch splits the contents of a text field (tokenizes) based on certain special characters. This is causing issues with search queries of the GCV database because we use special characters in our yucky names.

The special characters used for tokenizing are hard-coded and can't be disabled. Subsequently, the only way to prevent this tokenization is to explicitly escape all special characters in both the text stored in the database and in the text of a query. This is a cumbersome solution and is prone to errors due to the need for continuous developer intervention across current and future microservices.

Fortunately, there is also a tag field that doesn't tokenize based on any special characters, other than a configurable character that separates tags in a single field ("," by default). Although the search functionality of this field is more primitive, I don't think we were using many of the features of the text field to begin with. As such, the point of this issue is to update the Redis loader to use the tag field instead of the text field and to update all affected microservices.

**NOTE: A check should be added to the Redis Loader that prevents data from being loaded into an existing database using this new schema if there's already data in the database that uses the old schema.**

**Comment by alancleary** [comment]
It turns out the RediSearch tag field doesn't actually support search; it only does exact and prefix matching. This means it doesn't make sense for us to switch all of the text fields to tag fields. However, switching some fields still makes sense, specifically those that we want to match exactly, such as the family and chromosome of a gene. We'll want to keep the gene and chromosome names as text fields, though, to support inexact searching. These document can still be targeted exactly using their document keys since we're using their names as their keys.

**Comment by adf-ncgr** [comment]
Hmm, I may not be exactly following how this is going to work out but to make things concrete with a test case, here's 
1) a full gene id that should be matched exactly but returns nothing:
https://vigna.legumeinfo.org/tools/gcv/search?q=vigun.CB5-2.gnm1.ann1.VuCB5-2.03G051600&sources=vigna
2) stripping "the yucky" and using only the original name still gives nothing in this case, presumably because the original has it's own little problematic prefixing:
https://vigna.legumeinfo.org/tools/gcv/search?q=VuCB5-2.03G051600&sources=vigna 
3) using a further reduced substring:
https://vigna.legumeinfo.org/tools/gcv/search?q=03G051600&sources=vigna
returns several genes, among which the target gene is one of several.

If we can get it to work such that searches 1 and 2 return the target gene and 3 continues to behave as it does now, that would be good. I guess I'm less concerned about general fuzzy matching capabilities in this context than I am that exact substring matches such as the above should be respected (whether they are prefix or infix or suffix).

**Comment by alancleary** [comment]
Tags fields were introduced in commit 453a972e334fc8430a671f2f16baa0b0a18899fc.

**Comment by alancleary** [comment]
Updated the macro-synteny blocks and micro-synteny search fields to use tags in commit 55dc787bec779dcca4679b2a6d0a708d80f7b133.

**Comment by alancleary** [comment]
Updated the macro-synteny service to escape breakpoint characters before searching tags fields in commit 98c5809a2f00692a0a4ce43027a4bcddb15e191a.

**Comment by alancleary** [comment]
Ditto for the micro-synteny service in commit 2c67bb5ab1dc82db37d6048b2e9c16bc27c5b786. Closing.
