### ISSUE TITLE
Add DSCensor-OpenAPI as Microservice

### ISSUE THREAD

**Issue by ctcncgr** [legumeinfo/microservices#611]
Add a new microservice for the DSCensor RESTful API.

**Comment by alancleary** [comment]
Let me know if you want help/guidance hooking this into the automated builds the other services are using.

**Comment by adf-ncgr** [comment]
thanks @alancleary I told @ctcncgr to try to more or less follow the model of what I'd done on linkouts (following your model from other services but keeping the docker-compose files local to the repo instead of separating out as with gcv-docker-compose); but if you think there's a reason to look to something else as a template here feel free to suggest...

**Comment by alancleary** [comment]
The linkouts service should work as a template. One other thing that's worth mentioning explicitly is that I'm using [pip-tools](https://pypi.org/project/pip-tools/) to manage dependencies. So each service's `setup.cfg` file states its primary dependencies and then `pip-compile` (a command provided by pip-tools) generates the `requirements.txt` file with actual version information, including transitive dependencies.
